#  ____  __  __  ____         _____ __  __ _   _
# / ___||  \/  ||___ \       | ____|  \/  | | | |
# \___ \| |\/| |  __) |_____ |  _| | |\/| | | | |
#  ___) | |  | | / __/|_____|| |___| |  | | |_| |
# |____/|_|  |_||_____|      |_____|_|  |_|\___/
#
# sm2-emu — A Sega Model 2 arcade emulator.
# Copyright (c) 2025+ Daniel Martin (dmanlfc)
# SPDX-License-Identifier: BSD-3-Clause
#
# This header must not be removed. The source files in this project may not be
# used to contribute to commercial projects or for monetary gain without the
# express written permission of the author.
#

# Script-mode helper: turn a SPIR-V module into a C++ header holding it as a
# constexpr uint32_t array.
#
#   cmake -DSM2_IN=x.spv -DSM2_OUT=x.h -DSM2_SYMBOL=x -DSM2_SOURCE_NAME=x.frag
#         -P EmbedSpirv.cmake
#
# Embedding rather than loading at runtime means the binary has no external
# shader files to find, no runtime GLSL compiler, and a shader that fails to
# compile fails the build instead of the first frame.

foreach(var SM2_IN SM2_OUT SM2_SYMBOL)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "EmbedSpirv.cmake: ${var} is required")
    endif()
endforeach()

if(NOT DEFINED SM2_SOURCE_NAME)
    get_filename_component(SM2_SOURCE_NAME "${SM2_IN}" NAME)
endif()

file(READ "${SM2_IN}" hex HEX)
string(LENGTH "${hex}" hex_length)

math(EXPR byte_count "${hex_length} / 2")
math(EXPR remainder  "${byte_count} % 4")
if(NOT remainder EQUAL 0)
    message(FATAL_ERROR
        "EmbedSpirv.cmake: ${SM2_IN} is ${byte_count} bytes, "
        "which is not a whole number of 32-bit words")
endif()
math(EXPR word_count "${byte_count} / 4")

if(word_count EQUAL 0)
    message(FATAL_ERROR "EmbedSpirv.cmake: ${SM2_IN} is empty")
endif()

# SPIR-V magic 0x07230203 stored little-endian.
string(SUBSTRING "${hex}" 0 8 magic)
if(NOT magic STREQUAL "03022307")
    message(FATAL_ERROR
        "EmbedSpirv.cmake: ${SM2_IN} does not begin with the SPIR-V magic "
        "number (found ${magic}). Either the file is not SPIR-V or it was "
        "produced big-endian, which this project does not support.")
endif()

set(body "")
set(column 0)
foreach(word RANGE 1 ${word_count})
    math(EXPR offset "(${word} - 1) * 8")
    string(SUBSTRING "${hex}" ${offset} 8 raw)

    # Reverse the byte order: the file is little-endian, the literal is not.
    string(SUBSTRING "${raw}" 0 2 b0)
    string(SUBSTRING "${raw}" 2 2 b1)
    string(SUBSTRING "${raw}" 4 2 b2)
    string(SUBSTRING "${raw}" 6 2 b3)

    string(APPEND body "0x${b3}${b2}${b1}${b0}u,")

    math(EXPR column "${column} + 1")
    if(column EQUAL 8)
        string(APPEND body "\n    ")
        set(column 0)
    else()
        string(APPEND body " ")
    endif()
endforeach()

string(REGEX REPLACE "[ \n]+$" "" body "${body}")

get_filename_component(out_name "${SM2_OUT}" NAME)
string(TOUPPER "${out_name}" guard)
string(REGEX REPLACE "[^A-Za-z0-9]" "_" guard "${guard}")

file(WRITE "${SM2_OUT}"
"// Generated by cmake/EmbedSpirv.cmake. Do not edit.
// Source: ${SM2_SOURCE_NAME}
#ifndef SM2_GENERATED_${guard}
#define SM2_GENERATED_${guard}

#include <cstdint>

namespace sm2::shaders {

inline constexpr std::uint32_t ${SM2_SYMBOL}[] = {
    ${body}
};

inline constexpr std::uint32_t ${SM2_SYMBOL}WordCount =
    sizeof(${SM2_SYMBOL}) / sizeof(std::uint32_t);

}  // namespace sm2::shaders

#endif  // SM2_GENERATED_${guard}
")
