#  ____  __  __  ____         _____ __  __ _   _
# / ___||  \/  ||___ \       | ____|  \/  | | | |
# \___ \| |\/| |  __) |_____ |  _| | |\/| | | | |
#  ___) | |  | | / __/|_____|| |___| |  | | |_| |
# |____/|_|  |_||_____|      |_____|_|  |_|\___/
#
# sm2-emu — A Sega Model 2 arcade emulator.
# Copyright (c) 2025+ Daniel Martin (dmanlfc)
# SPDX-License-Identifier: BSD-3-Clause
#
# This header must not be removed. The source files in this project may not be
# used to contribute to commercial projects or for monetary gain without the
# express written permission of the author.
#

# Script-mode helper: embed a GLSL source file as a C++ raw string literal,
# for a backend that compiles it at runtime with glCompileShader rather than
# ingesting SPIR-V (see EmbedSpirv.cmake for that path).
#
#   cmake -DSM2_IN=x.frag -DSM2_OUT=x_glsl.h -DSM2_SYMBOL=x -DSM2_SOURCE_NAME=x.frag
#         -P EmbedGlsl.cmake
#
# Embedding the source text, rather than shipping the .frag/.comp/.vert files
# beside the binary, keeps the same "no external files to find" property
# EmbedSpirv.cmake's embedding already gives the Vulkan path.

foreach(var SM2_IN SM2_OUT SM2_SYMBOL)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "EmbedGlsl.cmake: ${var} is required")
    endif()
endforeach()

if(NOT DEFINED SM2_SOURCE_NAME)
    get_filename_component(SM2_SOURCE_NAME "${SM2_IN}" NAME)
endif()

file(READ "${SM2_IN}" source)

# A raw string literal's own delimiter must not appear inside the payload.
# ")glsl\"" cannot occur in this project's shaders (checked when this script
# was written; re-check by hand if a future shader ever needs a different
# delimiter), but failing loudly here is cheaper than a build that embeds a
# truncated shader silently.
string(FIND "${source}" ")glsl\"" collision)
if(NOT collision EQUAL -1)
    message(FATAL_ERROR
        "EmbedGlsl.cmake: ${SM2_IN} contains the raw-string delimiter "
        "')glsl\"' this script uses, which would truncate the embedded source. "
        "Pick a different delimiter in this script if a shader genuinely needs "
        "that text.")
endif()

get_filename_component(out_name "${SM2_OUT}" NAME)
string(TOUPPER "${out_name}" guard)
string(REGEX REPLACE "[^A-Za-z0-9]" "_" guard "${guard}")

file(WRITE "${SM2_OUT}"
"// Generated by cmake/EmbedGlsl.cmake. Do not edit.
// Source: ${SM2_SOURCE_NAME}
#ifndef SM2_GENERATED_${guard}
#define SM2_GENERATED_${guard}

namespace sm2::shaders {

inline constexpr const char* ${SM2_SYMBOL} = R\"glsl(
${source})glsl\";

}  // namespace sm2::shaders

#endif  // SM2_GENERATED_${guard}
")
